// vstmididrv.idl : IDL source for vstmididrv.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (vstmididrv.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	
	[
		object,
		uuid(E57454BC-953E-4152-B46C-F4E9CFD52D05),
		dual,
		helpstring("IVSTMIDIDirectMusicSynth Interface"),
		pointer_default(unique)
	]
	interface IVSTMIDIDirectMusicSynth : IDispatch
	{
	};
	
	[
		object,
		uuid(1279F245-4D9A-4AC9-A511-59145A3DAAF5),
		dual,
		helpstring("ISynthClassFactory Interface"),
		pointer_default(unique)
	]
	interface ISynthClassFactory : IDispatch
	{
	};

[
	uuid(38C2456C-17C0-41CE-9150-9520CE61AB42),
	version(1.0),
	helpstring("VSTMIDIDrv 1.0 Type Library")
]
library VSTMIDILib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	
	[
		uuid(E9062C64-6500-4D86-BD1D-2835F1E24589),
		helpstring("VSTMIDIDirectMusicSynth Class")
	]
	coclass VSTMIDIDirectMusicSynth
	{
		[default] interface IVSTMIDIDirectMusicSynth;
	};
	
	[
		uuid(4CA80ACD-FC44-4180-84D2-38C2E91B5463),
		helpstring("SynthClassFactory Class")
	]
	coclass SynthClassFactory
	{
		[default] interface ISynthClassFactory;
	};
};
